// Auto-generated by material_extractor/build_dashboard_data.py — do not edit by hand.
const parts = {
  "subassemblies": [
    {
      "id": "connect",
      "name": "Connectors & Interconnect",
      "description": "USB receptacle, housings, shorting plugs",
      "partCount": 3,
      "weight": 916.874,
      "parts": [
        {
          "part": "50-57-9404",
          "designators": "H9, H10",
          "weight": 500.001,
          "materials": [
            {
              "material": "Polycarbonate/PBT Blend (PC+PBT)",
              "weight": 260.435
            },
            {
              "material": "Glass Fiber",
              "weight": 165.218
            },
            {
              "material": "Flame Retardant (FR)",
              "weight": 46.087
            },
            {
              "material": "Antimony Trioxide (Sb2O3)",
              "weight": 16.087
            },
            {
              "material": "Additives (Undisclosed)",
              "weight": 6.087
            },
            {
              "material": "Additives (Trade Secret)",
              "weight": 6.087
            }
          ]
        },
        {
          "part": "1051640001",
          "designators": "J2",
          "weight": 233.6,
          "materials": [
            {
              "material": "Iron (Fe)",
              "weight": 132.666
            },
            {
              "material": "Chromium (Cr)",
              "weight": 35.131
            },
            {
              "material": "Nickel (Ni)",
              "weight": 20.48802
            },
            {
              "material": "Liquid Crystal Polymer (LCP)",
              "weight": 18.836
            },
            {
              "material": "Glass Fiber",
              "weight": 8.31
            },
            {
              "material": "Copper (Cu)",
              "weight": 7.95
            },
            {
              "material": "Tin (Sn)",
              "weight": 5.6
            },
            {
              "material": "Zinc (Zn)",
              "weight": 4.05
            },
            {
              "material": "Additives (Trade Secret)",
              "weight": 0.416
            },
            {
              "material": "Carbon Black",
              "weight": 0.139
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.008
            },
            {
              "material": "Gold (Au)",
              "weight": 0.006
            },
            {
              "material": "Cobalt (Co)",
              "weight": 2e-05
            }
          ]
        },
        {
          "part": "D3082-05",
          "designators": "TP26-TP29",
          "weight": 183.273,
          "materials": [
            {
              "material": "Copper (Cu)",
              "weight": 110.0
            },
            {
              "material": "Zinc (Zn)",
              "weight": 65.3
            },
            {
              "material": "Lead (Pb)",
              "weight": 3.58
            },
            {
              "material": "Tin (Sn)",
              "weight": 2.62
            },
            {
              "material": "Nickel (Ni)",
              "weight": 1.6
            },
            {
              "material": "Gold (Au)",
              "weight": 0.173
            }
          ]
        }
      ],
      "materials": [
        {
          "material": "Polycarbonate/PBT Blend (PC+PBT)",
          "category": "Polymer",
          "weight": 260.435
        },
        {
          "material": "Glass Fiber",
          "category": "Composite",
          "weight": 173.528
        },
        {
          "material": "Iron (Fe)",
          "category": "Metal",
          "weight": 132.666
        },
        {
          "material": "Copper (Cu)",
          "category": "Metal",
          "weight": 117.95
        },
        {
          "material": "Zinc (Zn)",
          "category": "Metal",
          "weight": 69.35
        },
        {
          "material": "Flame Retardant (FR)",
          "category": "Polymer Additive",
          "weight": 46.087
        },
        {
          "material": "Chromium (Cr)",
          "category": "Metal",
          "weight": 35.131
        },
        {
          "material": "Nickel (Ni)",
          "category": "Metal",
          "weight": 22.08802
        },
        {
          "material": "Liquid Crystal Polymer (LCP)",
          "category": "Polymer",
          "weight": 18.836
        },
        {
          "material": "Antimony Trioxide (Sb2O3)",
          "category": "Metal Oxide",
          "weight": 16.087
        },
        {
          "material": "Tin (Sn)",
          "category": "Metal",
          "weight": 8.22
        },
        {
          "material": "Additives (Trade Secret)",
          "category": "Additive",
          "weight": 6.503
        },
        {
          "material": "Additives (Undisclosed)",
          "category": "Additive",
          "weight": 6.087
        },
        {
          "material": "Lead (Pb)",
          "category": "Metal",
          "weight": 3.58
        },
        {
          "material": "Gold (Au)",
          "category": "Metal",
          "weight": 0.179
        },
        {
          "material": "Carbon Black",
          "category": "Filler",
          "weight": 0.139
        },
        {
          "material": "Palladium (Pd)",
          "category": "Metal",
          "weight": 0.008
        },
        {
          "material": "Cobalt (Co)",
          "category": "Metal",
          "weight": 2e-05
        }
      ]
    },
    {
      "id": "logic",
      "name": "Control & Logic ICs",
      "description": "Microcontroller, amplifiers, bus buffers, regulators",
      "partCount": 8,
      "weight": 350.3209,
      "parts": [
        {
          "part": "MSP430FR2355TPTR",
          "designators": "U4",
          "weight": 211.8473,
          "materials": [
            {
              "material": "Fused Silica (SiO2)",
              "weight": 106.168025
            },
            {
              "material": "Copper (Cu)",
              "weight": 83.508304
            },
            {
              "material": "Epoxy Resin",
              "weight": 14.378879
            },
            {
              "material": "Doped Silicon (Si)",
              "weight": 4.059463
            },
            {
              "material": "Iron (Fe)",
              "weight": 2.089496
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.793694
            },
            {
              "material": "Carbon Black",
              "weight": 0.361936
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.283458
            },
            {
              "material": "Zinc (Zn)",
              "weight": 0.11128
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.07062
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.01753
            },
            {
              "material": "Gold (Au)",
              "weight": 0.003416
            },
            {
              "material": "Chlorine (Cl)",
              "weight": 0.001206
            }
          ]
        },
        {
          "part": "INA240A2PWR",
          "designators": "U11",
          "weight": 41.472,
          "materials": [
            {
              "material": "Fused Silica (SiO2)",
              "weight": 21.344571
            },
            {
              "material": "Copper (Cu)",
              "weight": 12.6633
            },
            {
              "material": "Epoxy Resin",
              "weight": 3.419404
            },
            {
              "material": "Doped Silicon (Si)",
              "weight": 2.54743
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.622681
            },
            {
              "material": "Iron (Fe)",
              "weight": 0.312
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.247312
            },
            {
              "material": "Organic Phosphorus (Flame Retardant)",
              "weight": 0.136506
            },
            {
              "material": "Carbon Black",
              "weight": 0.074458
            },
            {
              "material": "Gold (Au)",
              "weight": 0.068953
            },
            {
              "material": "Zinc (Zn)",
              "weight": 0.013
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.01066
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.0039
            },
            {
              "material": "Lead (Pb)",
              "weight": 0.0039
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.0039
            }
          ]
        },
        {
          "part": "P82B96DGKR",
          "designators": "U9, U13",
          "weight": 26.754,
          "materials": [
            {
              "material": "Fused Silica (SiO2)",
              "weight": 12.608714
            },
            {
              "material": "Copper (Cu)",
              "weight": 9.65634
            },
            {
              "material": "Epoxy Resin",
              "weight": 2.262068
            },
            {
              "material": "Doped Silicon (Si)",
              "weight": 1.136361
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.520445
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.220359
            },
            {
              "material": "Zinc (Zn)",
              "weight": 0.102
            },
            {
              "material": "Silicon (Si)",
              "weight": 0.08976
            },
            {
              "material": "Gold (Au)",
              "weight": 0.079596
            },
            {
              "material": "Carbon Black",
              "weight": 0.044501
            },
            {
              "material": "Iron (Fe)",
              "weight": 0.0204
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.008364
            },
            {
              "material": "Lead (Pb)",
              "weight": 0.0051
            }
          ]
        },
        {
          "part": "TPS73033DBVR",
          "designators": "U10",
          "weight": 20.2573,
          "materials": [
            {
              "material": "Fused Silica (SiO2)",
              "weight": 9.752045
            },
            {
              "material": "Copper (Cu)",
              "weight": 7.80776
            },
            {
              "material": "Epoxy Resin",
              "weight": 1.493076
            },
            {
              "material": "Doped Silicon (Si)",
              "weight": 0.708979
            },
            {
              "material": "Iron (Fe)",
              "weight": 0.1784
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.14125
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.085608
            },
            {
              "material": "Gold (Au)",
              "weight": 0.06141
            },
            {
              "material": "Carbon Black",
              "weight": 0.011209
            },
            {
              "material": "Zinc (Zn)",
              "weight": 0.01104
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.00369
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.0028
            }
          ]
        },
        {
          "part": "LM27313XQMFNOPB",
          "designators": "U6",
          "weight": 18.2388,
          "materials": [
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 9.570072
            },
            {
              "material": "Copper (Cu)",
              "weight": 5.436408
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.923205
            },
            {
              "material": "Doped Silicon (Si)",
              "weight": 0.812161
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.7
            },
            {
              "material": "Metal Hydroxide",
              "weight": 0.323678
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.23427
            },
            {
              "material": "Iron (Fe)",
              "weight": 0.134065
            },
            {
              "material": "Gold (Au)",
              "weight": 0.064148
            },
            {
              "material": "Carbon Black",
              "weight": 0.032368
            },
            {
              "material": "Zinc (Zn)",
              "weight": 0.00676
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.00169
            }
          ]
        },
        {
          "part": "LMH6642MFNOPB",
          "designators": "U12",
          "weight": 17.8691,
          "materials": [
            {
              "material": "Fused Silica (SiO2)",
              "weight": 10.590836
            },
            {
              "material": "Copper (Cu)",
              "weight": 5.339234
            },
            {
              "material": "Epoxy Resin",
              "weight": 1.437979
            },
            {
              "material": "Doped Silicon (Si)",
              "weight": 0.212404
            },
            {
              "material": "Iron (Fe)",
              "weight": 0.14248
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.09
            },
            {
              "material": "Carbon Black",
              "weight": 0.036105
            },
            {
              "material": "Zinc (Zn)",
              "weight": 0.01096
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.00822
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.000603
            },
            {
              "material": "Chlorine (Cl)",
              "weight": 0.00012
            },
            {
              "material": "Gold (Au)",
              "weight": 0.000118
            }
          ]
        },
        {
          "part": "TMUX1219DCKR",
          "designators": "U1, U5, U7, U8",
          "weight": 10.8492,
          "materials": [
            {
              "material": "Copper (Cu)",
              "weight": 6.633286
            },
            {
              "material": "Fused Silica (SiO2)",
              "weight": 3.305448
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.442745
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.163
            },
            {
              "material": "Iron (Fe)",
              "weight": 0.149204
            },
            {
              "material": "Doped Silicon (Si)",
              "weight": 0.104107
            },
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 0.027533
            },
            {
              "material": "Carbon Black",
              "weight": 0.011306
            },
            {
              "material": "Zinc (Zn)",
              "weight": 0.008138
            },
            {
              "material": "Phenolic Resin",
              "weight": 0.002206
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.001763
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.000256
            },
            {
              "material": "Dicyandiamide (Curing Agent)",
              "weight": 0.000184
            },
            {
              "material": "Chlorine (Cl)",
              "weight": 3.8e-05
            },
            {
              "material": "Lead (Pb)",
              "weight": 7e-06
            },
            {
              "material": "Gold (Au)",
              "weight": 5e-06
            }
          ]
        },
        {
          "part": "TPD4E004DRYR",
          "designators": "U3",
          "weight": 3.0333,
          "materials": [
            {
              "material": "Copper (Cu)",
              "weight": 1.942577
            },
            {
              "material": "Fused Silica (SiO2)",
              "weight": 0.649084
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.132466
            },
            {
              "material": "Doped Silicon (Si)",
              "weight": 0.113669
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.093504
            },
            {
              "material": "Iron (Fe)",
              "weight": 0.04544
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.019975
            },
            {
              "material": "Gold (Au)",
              "weight": 0.008188
            },
            {
              "material": "Hydroxypropyl Methacrylate",
              "weight": 0.006203
            },
            {
              "material": "Carbon Black",
              "weight": 0.004416
            },
            {
              "material": "Organic Phosphorus (Flame Retardant)",
              "weight": 0.004416
            },
            {
              "material": "Polysiloxanes",
              "weight": 0.004416
            },
            {
              "material": "Zinc (Zn)",
              "weight": 0.00299
            },
            {
              "material": "Acid Anhydride",
              "weight": 0.00202
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.001993
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.000902
            },
            {
              "material": "Anatase (TiO2)",
              "weight": 0.000433
            },
            {
              "material": "Tripropylene Glycol Diacrylate",
              "weight": 0.000433
            },
            {
              "material": "Aluminum Nitride (AlN)",
              "weight": 0.000144
            }
          ]
        }
      ],
      "materials": [
        {
          "material": "Fused Silica (SiO2)",
          "category": "Metal Oxide",
          "weight": 164.418723
        },
        {
          "material": "Copper (Cu)",
          "category": "Metal",
          "weight": 132.987209
        },
        {
          "material": "Epoxy Resin",
          "category": "Polymer",
          "weight": 24.45086
        },
        {
          "material": "Silicon Dioxide (SiO2)",
          "category": "Metal Oxide",
          "weight": 9.702538
        },
        {
          "material": "Doped Silicon (Si)",
          "category": "Metalloid",
          "weight": 9.694574
        },
        {
          "material": "Iron (Fe)",
          "category": "Metal",
          "weight": 3.071485
        },
        {
          "material": "Silver (Ag)",
          "category": "Metal",
          "weight": 2.102254
        },
        {
          "material": "Nickel (Ni)",
          "category": "Metal",
          "weight": 1.156798
        },
        {
          "material": "Tin (Sn)",
          "category": "Metal",
          "weight": 0.8669
        },
        {
          "material": "Carbon Black",
          "category": "Filler",
          "weight": 0.576299
        },
        {
          "material": "Metal Hydroxide",
          "category": "Hydroxide",
          "weight": 0.323678
        },
        {
          "material": "Gold (Au)",
          "category": "Metal",
          "weight": 0.285834
        },
        {
          "material": "Zinc (Zn)",
          "category": "Metal",
          "weight": 0.266168
        },
        {
          "material": "Organic Phosphorus (Flame Retardant)",
          "category": "Polymer Additive",
          "weight": 0.140922
        },
        {
          "material": "Phosphorus (P)",
          "category": "Non-Metal",
          "weight": 0.090986
        },
        {
          "material": "Silicon (Si)",
          "category": "Metalloid",
          "weight": 0.08976
        },
        {
          "material": "Palladium (Pd)",
          "category": "Metal",
          "weight": 0.042005
        },
        {
          "material": "Aluminum Oxide (Al2O3)",
          "category": "Metal Oxide",
          "weight": 0.027533
        },
        {
          "material": "Lead (Pb)",
          "category": "Metal",
          "weight": 0.009007
        },
        {
          "material": "Hydroxypropyl Methacrylate",
          "category": "Polymer",
          "weight": 0.006203
        },
        {
          "material": "Polysiloxanes",
          "category": "Polymer",
          "weight": 0.004416
        },
        {
          "material": "Phenolic Resin",
          "category": "Polymer",
          "weight": 0.002206
        },
        {
          "material": "Acid Anhydride",
          "category": "Polymer Additive",
          "weight": 0.00202
        },
        {
          "material": "Chlorine (Cl)",
          "category": "Halogen",
          "weight": 0.001364
        },
        {
          "material": "Anatase (TiO2)",
          "category": "Metal Oxide",
          "weight": 0.000433
        },
        {
          "material": "Tripropylene Glycol Diacrylate",
          "category": "Polymer",
          "weight": 0.000433
        },
        {
          "material": "Dicyandiamide (Curing Agent)",
          "category": "Polymer Additive",
          "weight": 0.000184
        },
        {
          "material": "Aluminum Nitride (AlN)",
          "category": "Ceramic",
          "weight": 0.000144
        }
      ]
    },
    {
      "id": "power",
      "name": "Power Stage",
      "description": "MOSFET, Schottky and Zener diodes",
      "partCount": 3,
      "weight": 228.7662,
      "parts": [
        {
          "part": "RBR3LAM40ATR",
          "designators": "D1",
          "weight": 217.3441,
          "materials": [
            {
              "material": "Lead (Pb)",
              "weight": 217.3441
            }
          ]
        },
        {
          "part": "BUK6D43-40PX",
          "designators": "Q1",
          "weight": 6.9121,
          "materials": [
            {
              "material": "Copper (Cu)",
              "weight": 2.750344
            },
            {
              "material": "Fused Silica (SiO2)",
              "weight": 2.238
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.8579
            },
            {
              "material": "Silicon (Si)",
              "weight": 0.516276
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.169898
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.158366
            },
            {
              "material": "Aluminum Hydroxide (Al(OH)3)",
              "weight": 0.1119
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.056
            },
            {
              "material": "Bismuth (Bi)",
              "weight": 0.01865
            },
            {
              "material": "Carbon Black",
              "weight": 0.01865
            },
            {
              "material": "Poly(isobornyl methacrylate) (PIBMA)",
              "weight": 0.007
            },
            {
              "material": "Magnesium (Mg)",
              "weight": 0.004217
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.003273
            },
            {
              "material": "Gold (Au)",
              "weight": 0.000962
            },
            {
              "material": "Polysiloxanes",
              "weight": 0.0007
            },
            {
              "material": "Lead (Pb)",
              "weight": 8e-06
            }
          ]
        },
        {
          "part": "SZMM3Z10VST1G",
          "designators": "D8",
          "weight": 4.51,
          "materials": [
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 2.416
            },
            {
              "material": "Silicon (Si)",
              "weight": 0.49
            },
            {
              "material": "Iron (Fe)",
              "weight": 0.4317
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.3122
            },
            {
              "material": "Epoxy Resin (o-Cresol Novolac)",
              "weight": 0.2416
            },
            {
              "material": "Phenolic Resin",
              "weight": 0.1359
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.13
            },
            {
              "material": "Copper (Cu)",
              "weight": 0.1261
            },
            {
              "material": "Boron Zinc Hydroxide Oxide",
              "weight": 0.0906
            },
            {
              "material": "Melamine-Based Flame Retardant",
              "weight": 0.0906
            },
            {
              "material": "Carbon Black",
              "weight": 0.0302
            },
            {
              "material": "Zinc Oxide (ZnO)",
              "weight": 0.0151
            }
          ]
        }
      ],
      "materials": [
        {
          "material": "Lead (Pb)",
          "category": "Metal",
          "weight": 217.344108
        },
        {
          "material": "Silicon Dioxide (SiO2)",
          "category": "Metal Oxide",
          "weight": 3.2739
        },
        {
          "material": "Copper (Cu)",
          "category": "Metal",
          "weight": 2.876444
        },
        {
          "material": "Fused Silica (SiO2)",
          "category": "Metal Oxide",
          "weight": 2.238
        },
        {
          "material": "Silicon (Si)",
          "category": "Metalloid",
          "weight": 1.006276
        },
        {
          "material": "Nickel (Ni)",
          "category": "Metal",
          "weight": 0.470566
        },
        {
          "material": "Iron (Fe)",
          "category": "Metal",
          "weight": 0.4317
        },
        {
          "material": "Tin (Sn)",
          "category": "Metal",
          "weight": 0.299898
        },
        {
          "material": "Epoxy Resin (o-Cresol Novolac)",
          "category": "Polymer",
          "weight": 0.2416
        },
        {
          "material": "Phenolic Resin",
          "category": "Polymer",
          "weight": 0.1359
        },
        {
          "material": "Aluminum Hydroxide (Al(OH)3)",
          "category": "Hydroxide",
          "weight": 0.1119
        },
        {
          "material": "Boron Zinc Hydroxide Oxide",
          "category": "Hydroxide",
          "weight": 0.0906
        },
        {
          "material": "Melamine-Based Flame Retardant",
          "category": "Additive",
          "weight": 0.0906
        },
        {
          "material": "Silver (Ag)",
          "category": "Metal",
          "weight": 0.056
        },
        {
          "material": "Carbon Black",
          "category": "Filler",
          "weight": 0.04885
        },
        {
          "material": "Bismuth (Bi)",
          "category": "Metal",
          "weight": 0.01865
        },
        {
          "material": "Zinc Oxide (ZnO)",
          "category": "Metal Oxide",
          "weight": 0.0151
        },
        {
          "material": "Poly(isobornyl methacrylate) (PIBMA)",
          "category": "Polymer",
          "weight": 0.007
        },
        {
          "material": "Magnesium (Mg)",
          "category": "Metal",
          "weight": 0.004217
        },
        {
          "material": "Palladium (Pd)",
          "category": "Metal",
          "weight": 0.003273
        },
        {
          "material": "Gold (Au)",
          "category": "Metal",
          "weight": 0.000962
        },
        {
          "material": "Polysiloxanes",
          "category": "Polymer",
          "weight": 0.0007
        }
      ]
    },
    {
      "id": "opto",
      "name": "Optoelectronics",
      "description": "Indicator LEDs",
      "partCount": 4,
      "weight": 122.9573,
      "parts": [
        {
          "part": "150060BS75000",
          "designators": "D9",
          "weight": 60.0,
          "materials": [
            {
              "material": "Epoxy Resin (Bisphenol A DGEBA)",
              "weight": 20.0
            },
            {
              "material": "Gold (Au)",
              "weight": 10.1
            },
            {
              "material": "Copper (Cu)",
              "weight": 5.5
            },
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 4.7
            },
            {
              "material": "Nickel (Ni)",
              "weight": 4.4
            },
            {
              "material": "Gallium Nitride (GaN)",
              "weight": 3.5
            },
            {
              "material": "Epoxy Resin (Phenol-Formaldehyde)",
              "weight": 3.153
            },
            {
              "material": "Additives (Trade Secret)",
              "weight": 2.8
            },
            {
              "material": "Epoxy Resin (o-Cresol Novolac)",
              "weight": 2.047
            },
            {
              "material": "Glass Fiber",
              "weight": 2.0
            },
            {
              "material": "Indium Nitride (InN)",
              "weight": 1.8
            }
          ]
        },
        {
          "part": "150080VS75000",
          "designators": "D2, D4",
          "weight": 60.0,
          "materials": [
            {
              "material": "Epoxy Resin (Bisphenol A DGEBA)",
              "weight": 12.8
            },
            {
              "material": "Gold (Au)",
              "weight": 10.1
            },
            {
              "material": "Silver (Ag)",
              "weight": 7.5
            },
            {
              "material": "Copper (Cu)",
              "weight": 5.5
            },
            {
              "material": "Epoxy Resin (Phenol-Formaldehyde)",
              "weight": 5.053
            },
            {
              "material": "Indium (In)",
              "weight": 4.8
            },
            {
              "material": "Nickel (Ni)",
              "weight": 4.4
            },
            {
              "material": "Gallium (Ga)",
              "weight": 2.6
            },
            {
              "material": "Epoxy Resin (o-Cresol Novolac)",
              "weight": 2.047
            },
            {
              "material": "Glass Fiber",
              "weight": 2.0
            },
            {
              "material": "Aluminum (Al)",
              "weight": 1.7
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.9
            },
            {
              "material": "Additives (Trade Secret)",
              "weight": 0.6
            }
          ]
        },
        {
          "part": "LTST-C190KRKT",
          "designators": "D6",
          "weight": 1.497,
          "materials": [
            {
              "material": "Epoxy Resin (Bisphenol A DGEBA)",
              "weight": 0.5256
            },
            {
              "material": "Copper (Cu)",
              "weight": 0.20468
            },
            {
              "material": "Acid Anhydride",
              "weight": 0.1872
            },
            {
              "material": "Glass Fiber",
              "weight": 0.160384
            },
            {
              "material": "Cured Thermosetting Resin",
              "weight": 0.160384
            },
            {
              "material": "Gallium Arsenide (GaAs)",
              "weight": 0.101803
            },
            {
              "material": "Gold (Au)",
              "weight": 0.088529
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.040638
            },
            {
              "material": "Barium (Ba)",
              "weight": 0.01036
            },
            {
              "material": "BHT (Antioxidant)",
              "weight": 0.0072
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.0025
            },
            {
              "material": "Phosphorus (P)",
              "weight": 0.001988
            },
            {
              "material": "Gallium (Ga)",
              "weight": 0.001765
            },
            {
              "material": "Adhesion Promoter",
              "weight": 0.00125
            },
            {
              "material": "Phenolic Resin",
              "weight": 0.00125
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.000392
            },
            {
              "material": "Indium Oxide (In2O3)",
              "weight": 0.000306
            },
            {
              "material": "Aluminum (Al)",
              "weight": 0.000306
            },
            {
              "material": "Dicyandiamide (Curing Agent)",
              "weight": 0.00025
            },
            {
              "material": "Indium Tin Oxide (ITO)",
              "weight": 0.000202
            },
            {
              "material": "Others",
              "weight": 8e-06
            },
            {
              "material": "Chromium (Cr)",
              "weight": 3e-06
            }
          ]
        },
        {
          "part": "LTST-C190KGKT",
          "designators": "D7",
          "weight": 1.4604,
          "materials": [
            {
              "material": "Epoxy Resin",
              "weight": 0.42365
            },
            {
              "material": "Glass Fiber",
              "weight": 0.3654
            },
            {
              "material": "Copper (Cu)",
              "weight": 0.28143
            },
            {
              "material": "Curing Agent (THPA)",
              "weight": 0.1806
            },
            {
              "material": "Gallium Arsenide (GaAs)",
              "weight": 0.06889
            },
            {
              "material": "Gold (Au)",
              "weight": 0.053242
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.036694
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.030593
            },
            {
              "material": "Indium (In)",
              "weight": 0.006474
            },
            {
              "material": "Epoxy Resin (TGIC)",
              "weight": 0.0051
            },
            {
              "material": "Aluminum (Al)",
              "weight": 0.003071
            },
            {
              "material": "Gallium Phosphide (GaP)",
              "weight": 0.002656
            },
            {
              "material": "Solvent (Aromatic Naphtha)",
              "weight": 0.00255
            }
          ]
        }
      ],
      "materials": [
        {
          "material": "Epoxy Resin (Bisphenol A DGEBA)",
          "category": "Polymer",
          "weight": 33.3256
        },
        {
          "material": "Gold (Au)",
          "category": "Metal",
          "weight": 20.341771
        },
        {
          "material": "Copper (Cu)",
          "category": "Metal",
          "weight": 11.48611
        },
        {
          "material": "Nickel (Ni)",
          "category": "Metal",
          "weight": 8.830985
        },
        {
          "material": "Epoxy Resin (Phenol-Formaldehyde)",
          "category": "Polymer",
          "weight": 8.206
        },
        {
          "material": "Silver (Ag)",
          "category": "Metal",
          "weight": 7.577332
        },
        {
          "material": "Indium (In)",
          "category": "Metal",
          "weight": 4.806474
        },
        {
          "material": "Aluminum Oxide (Al2O3)",
          "category": "Metal Oxide",
          "weight": 4.7
        },
        {
          "material": "Glass Fiber",
          "category": "Composite",
          "weight": 4.525784
        },
        {
          "material": "Epoxy Resin (o-Cresol Novolac)",
          "category": "Polymer",
          "weight": 4.094
        },
        {
          "material": "Gallium Nitride (GaN)",
          "category": "Compound Semiconductor",
          "weight": 3.5
        },
        {
          "material": "Additives (Trade Secret)",
          "category": "Additive",
          "weight": 3.4
        },
        {
          "material": "Gallium (Ga)",
          "category": "Metal",
          "weight": 2.601765
        },
        {
          "material": "Indium Nitride (InN)",
          "category": "Compound Semiconductor",
          "weight": 1.8
        },
        {
          "material": "Aluminum (Al)",
          "category": "Metal",
          "weight": 1.703377
        },
        {
          "material": "Phosphorus (P)",
          "category": "Non-Metal",
          "weight": 0.901988
        },
        {
          "material": "Epoxy Resin",
          "category": "Polymer",
          "weight": 0.42615
        },
        {
          "material": "Acid Anhydride",
          "category": "Polymer Additive",
          "weight": 0.1872
        },
        {
          "material": "Curing Agent (THPA)",
          "category": "Polymer Additive",
          "weight": 0.1806
        },
        {
          "material": "Gallium Arsenide (GaAs)",
          "category": "Compound Semiconductor",
          "weight": 0.170693
        },
        {
          "material": "Cured Thermosetting Resin",
          "category": "Polymer",
          "weight": 0.160384
        },
        {
          "material": "Barium (Ba)",
          "category": "Metal",
          "weight": 0.01036
        },
        {
          "material": "BHT (Antioxidant)",
          "category": "Additive",
          "weight": 0.0072
        },
        {
          "material": "Epoxy Resin (TGIC)",
          "category": "Polymer",
          "weight": 0.0051
        },
        {
          "material": "Gallium Phosphide (GaP)",
          "category": "Compound Semiconductor",
          "weight": 0.002656
        },
        {
          "material": "Solvent (Aromatic Naphtha)",
          "category": "Solvent",
          "weight": 0.00255
        },
        {
          "material": "Adhesion Promoter",
          "category": "Additive",
          "weight": 0.00125
        },
        {
          "material": "Phenolic Resin",
          "category": "Polymer",
          "weight": 0.00125
        },
        {
          "material": "Indium Oxide (In2O3)",
          "category": "Metal Oxide",
          "weight": 0.000306
        },
        {
          "material": "Dicyandiamide (Curing Agent)",
          "category": "Polymer Additive",
          "weight": 0.00025
        },
        {
          "material": "Indium Tin Oxide (ITO)",
          "category": "Metal Oxide",
          "weight": 0.000202
        },
        {
          "material": "Others",
          "category": "Unknown",
          "weight": 8e-06
        },
        {
          "material": "Chromium (Cr)",
          "category": "Metal",
          "weight": 3e-06
        }
      ]
    },
    {
      "id": "caps",
      "name": "Capacitors (MLCC)",
      "description": "Multilayer ceramic chip capacitors",
      "partCount": 6,
      "weight": 97.1432,
      "parts": [
        {
          "part": "885012207103",
          "designators": "C15",
          "weight": 56.35,
          "materials": [
            {
              "material": "Nickel (Ni)",
              "weight": 20.286
            },
            {
              "material": "Barium Titanate (BaTiO3)",
              "weight": 13.2986
            },
            {
              "material": "Tin (Sn)",
              "weight": 11.27
            },
            {
              "material": "Copper (Cu)",
              "weight": 9.9176
            },
            {
              "material": "Glass Fiber",
              "weight": 1.3524
            },
            {
              "material": "Yttrium Oxide (Y2O3)",
              "weight": 0.2254
            }
          ]
        },
        {
          "part": "CL31B105KCHNNNE",
          "designators": "C17",
          "weight": 21.5,
          "materials": [
            {
              "material": "Barium Titanate (BaTiO3)",
              "weight": 20.025
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.997
            },
            {
              "material": "Copper (Cu)",
              "weight": 0.337
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.141
            }
          ]
        },
        {
          "part": "EMK107B7105KAHT",
          "designators": "C9, C26",
          "weight": 6.5,
          "materials": [
            {
              "material": "Barium Titanate (BaTiO3)",
              "weight": 5.33
            },
            {
              "material": "Nickel (Ni)",
              "weight": 1.09
            },
            {
              "material": "Copper (Cu)",
              "weight": 0.04
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.04
            }
          ]
        },
        {
          "part": "EMK107BB7225KA-T",
          "designators": "C16",
          "weight": 6.5,
          "materials": [
            {
              "material": "Barium Titanate (BaTiO3)",
              "weight": 5.33
            },
            {
              "material": "Nickel (Ni)",
              "weight": 1.09
            },
            {
              "material": "Copper (Cu)",
              "weight": 0.04
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.04
            }
          ]
        },
        {
          "part": "0603ZC104KAT2A",
          "designators": "C7, C8, C10, C11, C13",
          "weight": 5.0932,
          "materials": [
            {
              "material": "Barium Oxide (BaO)",
              "weight": 2.8236
            },
            {
              "material": "Anatase (TiO2)",
              "weight": 1.4005
            },
            {
              "material": "Copper Oxide (CuO)",
              "weight": 0.35175
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.3184
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.12835
            },
            {
              "material": "Yttrium Oxide (Y2O3)",
              "weight": 0.0385
            },
            {
              "material": "Zinc Oxide (ZnO)",
              "weight": 0.00765
            },
            {
              "material": "Calcium Oxide (CaO)",
              "weight": 0.0076
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.0045
            },
            {
              "material": "Antimony Trioxide (Sb2O3)",
              "weight": 0.00365
            },
            {
              "material": "Manganese Dioxide (MnO2)",
              "weight": 0.0025
            },
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 0.00245
            },
            {
              "material": "Zirconium Dioxide (ZrO2)",
              "weight": 0.002
            },
            {
              "material": "Strontium Oxide (SrO)",
              "weight": 0.0008
            },
            {
              "material": "Sulphur Trioxide (SO3)",
              "weight": 0.00075
            },
            {
              "material": "Tricobalt Tetraoxide (Co3O4)",
              "weight": 0.0002
            }
          ]
        },
        {
          "part": "C0402C102J3GACTU",
          "designators": "C25",
          "weight": 1.2,
          "materials": [
            {
              "material": "Calcium Zirconate (CaZrO3)",
              "weight": 0.89
            },
            {
              "material": "Additives (Undisclosed)",
              "weight": 0.16
            },
            {
              "material": "Electrode Paste (Ni)",
              "weight": 0.06
            },
            {
              "material": "Finish Plating (Sn)",
              "weight": 0.05
            },
            {
              "material": "Under Layer (Ni)",
              "weight": 0.03
            },
            {
              "material": "Base Metal (Cu)",
              "weight": 0.01
            }
          ]
        }
      ],
      "materials": [
        {
          "material": "Barium Titanate (BaTiO3)",
          "category": "Ceramic",
          "weight": 43.9836
        },
        {
          "material": "Nickel (Ni)",
          "category": "Metal",
          "weight": 23.7814
        },
        {
          "material": "Tin (Sn)",
          "category": "Metal",
          "weight": 11.61935
        },
        {
          "material": "Copper (Cu)",
          "category": "Metal",
          "weight": 10.3346
        },
        {
          "material": "Barium Oxide (BaO)",
          "category": "Metal Oxide",
          "weight": 2.8236
        },
        {
          "material": "Anatase (TiO2)",
          "category": "Metal Oxide",
          "weight": 1.4005
        },
        {
          "material": "Glass Fiber",
          "category": "Composite",
          "weight": 1.3524
        },
        {
          "material": "Calcium Zirconate (CaZrO3)",
          "category": "Ceramic",
          "weight": 0.89
        },
        {
          "material": "Copper Oxide (CuO)",
          "category": "Metal Oxide",
          "weight": 0.35175
        },
        {
          "material": "Yttrium Oxide (Y2O3)",
          "category": "Metal Oxide",
          "weight": 0.2639
        },
        {
          "material": "Additives (Undisclosed)",
          "category": "Additive",
          "weight": 0.16
        },
        {
          "material": "Electrode Paste (Ni)",
          "category": "Paste",
          "weight": 0.06
        },
        {
          "material": "Finish Plating (Sn)",
          "category": "Plating",
          "weight": 0.05
        },
        {
          "material": "Under Layer (Ni)",
          "category": "Plating",
          "weight": 0.03
        },
        {
          "material": "Base Metal (Cu)",
          "category": "Metal",
          "weight": 0.01
        },
        {
          "material": "Zinc Oxide (ZnO)",
          "category": "Metal Oxide",
          "weight": 0.00765
        },
        {
          "material": "Calcium Oxide (CaO)",
          "category": "Metal Oxide",
          "weight": 0.0076
        },
        {
          "material": "Magnesium Oxide (MgO)",
          "category": "Metal Oxide",
          "weight": 0.0045
        },
        {
          "material": "Antimony Trioxide (Sb2O3)",
          "category": "Metal Oxide",
          "weight": 0.00365
        },
        {
          "material": "Manganese Dioxide (MnO2)",
          "category": "Metal Oxide",
          "weight": 0.0025
        },
        {
          "material": "Aluminum Oxide (Al2O3)",
          "category": "Metal Oxide",
          "weight": 0.00245
        },
        {
          "material": "Zirconium Dioxide (ZrO2)",
          "category": "Metal Oxide",
          "weight": 0.002
        },
        {
          "material": "Strontium Oxide (SrO)",
          "category": "Metal Oxide",
          "weight": 0.0008
        },
        {
          "material": "Sulphur Trioxide (SO3)",
          "category": "Metal Oxide",
          "weight": 0.00075
        },
        {
          "material": "Tricobalt Tetraoxide (Co3O4)",
          "category": "Metal Oxide",
          "weight": 0.0002
        }
      ]
    },
    {
      "id": "res",
      "name": "Resistors",
      "description": "Thick/thin film chip resistors",
      "partCount": 9,
      "weight": 29.9345,
      "parts": [
        {
          "part": "RCA12060000ZSEA",
          "designators": "R36",
          "weight": 8.7882,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 7.6101
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.35375
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.27423
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.23743
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.14766
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.07878
            },
            {
              "material": "Lead-Containing Glass Frit",
              "weight": 0.06232
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.01725
            },
            {
              "material": "Copper Oxide (CuO)",
              "weight": 0.00576
            },
            {
              "material": "Chromium Oxide (Cr2O3)",
              "weight": 0.00095
            },
            {
              "material": "Copper (Cu)",
              "weight": 1e-05
            },
            {
              "material": "Chromium (Cr)",
              "weight": 0.0
            }
          ]
        },
        {
          "part": "HCJ0805ZT0R00",
          "designators": "R1",
          "weight": 7.59,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 4.3718
            },
            {
              "material": "Copper (Cu)",
              "weight": 2.6208
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.1442
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.1366
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.0972
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.0882
            },
            {
              "material": "Barium Sulfate (BaSO4)",
              "weight": 0.0668
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.0455
            },
            {
              "material": "Solvent (Aromatic Naphtha)",
              "weight": 0.0152
            },
            {
              "material": "Chromium (Cr)",
              "weight": 0.0021
            },
            {
              "material": "Pigment (Unknown 1)",
              "weight": 0.0008
            },
            {
              "material": "Pigment (Unknown 2)",
              "weight": 0.0008
            }
          ]
        },
        {
          "part": "RC0603JR-07470RL",
          "designators": "R32, R33",
          "weight": 2.4734,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 2.1312
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.10336
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.05405
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.0444
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.0444
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.03211
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.02858
            },
            {
              "material": "Lead-Free Glass (Bi-Si-B)",
              "weight": 0.02137
            },
            {
              "material": "Ruthenium Oxide (RuO2)",
              "weight": 0.01092
            },
            {
              "material": "Lead-Containing Glass Frit",
              "weight": 0.00273
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.00032
            }
          ]
        },
        {
          "part": "RT0603BRC07500RL",
          "designators": "R28",
          "weight": 2.1277,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 1.85795
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.0651
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.06307
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.05613
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.03213
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.02919
            },
            {
              "material": "Calcium Oxide (CaO)",
              "weight": 0.01161
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.00968
            },
            {
              "material": "Lead-Free Glass (Bi-Si-B)",
              "weight": 0.00144
            },
            {
              "material": "Chromium (Cr)",
              "weight": 0.00067
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.0006
            },
            {
              "material": "Lead-Containing Glass Frit",
              "weight": 0.0001
            },
            {
              "material": "Silicon (Si)",
              "weight": 6e-05
            }
          ]
        },
        {
          "part": "RT0603DRE07117KL",
          "designators": "R4",
          "weight": 2.1277,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 1.85795
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.0651
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.06307
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.05613
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.03213
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.02919
            },
            {
              "material": "Calcium Oxide (CaO)",
              "weight": 0.01161
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.00968
            },
            {
              "material": "Lead-Free Glass (Bi-Si-B)",
              "weight": 0.00144
            },
            {
              "material": "Chromium (Cr)",
              "weight": 0.00067
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.0006
            },
            {
              "material": "Lead-Containing Glass Frit",
              "weight": 0.0001
            },
            {
              "material": "Silicon (Si)",
              "weight": 6e-05
            }
          ]
        },
        {
          "part": "RT0603DRE0713K3L",
          "designators": "R7",
          "weight": 2.1277,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 1.85795
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.0651
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.06307
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.05613
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.03213
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.02919
            },
            {
              "material": "Calcium Oxide (CaO)",
              "weight": 0.01161
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.00968
            },
            {
              "material": "Lead-Free Glass (Bi-Si-B)",
              "weight": 0.00144
            },
            {
              "material": "Chromium (Cr)",
              "weight": 0.00067
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.0006
            },
            {
              "material": "Lead-Containing Glass Frit",
              "weight": 0.0001
            },
            {
              "material": "Silicon (Si)",
              "weight": 6e-05
            }
          ]
        },
        {
          "part": "CRCW060310K0JNEA",
          "designators": "R35",
          "weight": 2.0398,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 1.73908
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.07437
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.0741
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.05721
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.03451
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.02355
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.014
            },
            {
              "material": "Lead-Containing Glass Frit",
              "weight": 0.01229
            },
            {
              "material": "Ruthenium Oxide (RuO2)",
              "weight": 0.00363
            },
            {
              "material": "Calcium Oxide (CaO)",
              "weight": 0.00362
            },
            {
              "material": "Carbon Black",
              "weight": 0.0018
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.00081
            },
            {
              "material": "Glass Oxide",
              "weight": 0.00057
            },
            {
              "material": "Chromium (Cr)",
              "weight": 0.00022
            },
            {
              "material": "Copper (Cu)",
              "weight": 9e-05
            }
          ]
        },
        {
          "part": "CRCW0603150KFKEA",
          "designators": "R8, R9, R15, R16",
          "weight": 2.0398,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 1.73908
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.07437
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.0741
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.05721
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.03451
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.02355
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.014
            },
            {
              "material": "Lead-Containing Glass Frit",
              "weight": 0.01229
            },
            {
              "material": "Ruthenium Oxide (RuO2)",
              "weight": 0.00363
            },
            {
              "material": "Calcium Oxide (CaO)",
              "weight": 0.00362
            },
            {
              "material": "Carbon Black",
              "weight": 0.0018
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.00081
            },
            {
              "material": "Glass Oxide",
              "weight": 0.00057
            },
            {
              "material": "Chromium (Cr)",
              "weight": 0.00022
            },
            {
              "material": "Copper (Cu)",
              "weight": 9e-05
            }
          ]
        },
        {
          "part": "CRCW0402680RJNED",
          "designators": "R34",
          "weight": 0.6199,
          "materials": [
            {
              "material": "Aluminum Oxide (Al2O3)",
              "weight": 0.48894
            },
            {
              "material": "Nickel (Ni)",
              "weight": 0.03326
            },
            {
              "material": "Tin (Sn)",
              "weight": 0.03311
            },
            {
              "material": "Silver (Ag)",
              "weight": 0.02189
            },
            {
              "material": "Silicon Dioxide (SiO2)",
              "weight": 0.01853
            },
            {
              "material": "Epoxy Resin",
              "weight": 0.00936
            },
            {
              "material": "Lead-Containing Glass Frit",
              "weight": 0.00596
            },
            {
              "material": "Magnesium Oxide (MgO)",
              "weight": 0.00407
            },
            {
              "material": "Ruthenium Oxide (RuO2)",
              "weight": 0.00216
            },
            {
              "material": "Calcium Oxide (CaO)",
              "weight": 0.00102
            },
            {
              "material": "Palladium (Pd)",
              "weight": 0.00063
            },
            {
              "material": "Glass Oxide",
              "weight": 0.00049
            },
            {
              "material": "Carbon Black",
              "weight": 0.00039
            },
            {
              "material": "Chromium (Cr)",
              "weight": 9e-05
            },
            {
              "material": "Copper (Cu)",
              "weight": 4e-05
            }
          ]
        }
      ],
      "materials": [
        {
          "material": "Aluminum Oxide (Al2O3)",
          "category": "Metal Oxide",
          "weight": 23.65405
        },
        {
          "material": "Copper (Cu)",
          "category": "Metal",
          "weight": 2.62103
        },
        {
          "material": "Silicon Dioxide (SiO2)",
          "category": "Metal Oxide",
          "weight": 0.83609
        },
        {
          "material": "Tin (Sn)",
          "category": "Metal",
          "weight": 0.796
        },
        {
          "material": "Nickel (Ni)",
          "category": "Metal",
          "weight": 0.71652
        },
        {
          "material": "Silver (Ag)",
          "category": "Metal",
          "weight": 0.44802
        },
        {
          "material": "Epoxy Resin",
          "category": "Polymer",
          "weight": 0.32378
        },
        {
          "material": "Magnesium Oxide (MgO)",
          "category": "Metal Oxide",
          "weight": 0.24889
        },
        {
          "material": "Lead-Containing Glass Frit",
          "category": "Glass",
          "weight": 0.09589
        },
        {
          "material": "Barium Sulfate (BaSO4)",
          "category": "Salt",
          "weight": 0.0668
        },
        {
          "material": "Calcium Oxide (CaO)",
          "category": "Metal Oxide",
          "weight": 0.04309
        },
        {
          "material": "Lead-Free Glass (Bi-Si-B)",
          "category": "Glass",
          "weight": 0.02569
        },
        {
          "material": "Ruthenium Oxide (RuO2)",
          "category": "Metal Oxide",
          "weight": 0.02034
        },
        {
          "material": "Solvent (Aromatic Naphtha)",
          "category": "Solvent",
          "weight": 0.0152
        },
        {
          "material": "Copper Oxide (CuO)",
          "category": "Metal Oxide",
          "weight": 0.00576
        },
        {
          "material": "Chromium (Cr)",
          "category": "Metal",
          "weight": 0.00464
        },
        {
          "material": "Palladium (Pd)",
          "category": "Metal",
          "weight": 0.00437
        },
        {
          "material": "Carbon Black",
          "category": "Filler",
          "weight": 0.00399
        },
        {
          "material": "Glass Oxide",
          "category": "Glass",
          "weight": 0.00163
        },
        {
          "material": "Chromium Oxide (Cr2O3)",
          "category": "Metal Oxide",
          "weight": 0.00095
        },
        {
          "material": "Pigment (Unknown 1)",
          "category": "Pigment",
          "weight": 0.0008
        },
        {
          "material": "Pigment (Unknown 2)",
          "category": "Pigment",
          "weight": 0.0008
        },
        {
          "material": "Silicon (Si)",
          "category": "Metalloid",
          "weight": 0.00018
        }
      ]
    }
  ],
  "partCount": 33,
  "totalWeight": 1745.9961
};
export default parts;
