"""Generate Dashboard/lib/parts.js from material_extractor/output/all_materials.csv.

Groups the extracted per-part material rows into functional sub-assemblies so the
dashboard can rank them by recoverable value. The sub-assembly map is keyed by
part number (= source datasheet filename) and is derived from the MC121EVM BOM
Report designators/descriptions.
"""

import csv
import json
import collections
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "material_extractor" / "output" / "all_materials.csv"
DEST = ROOT / "Dashboard" / "lib" / "parts.js"

# part number -> (sub-assembly id, BOM designators)
SUBASSEMBLY = {
    # --- Control & Logic ICs -------------------------------------------------
    "MSP430FR2355TPTR": ("logic", "U4"),
    "INA240A2PWR": ("logic", "U11"),
    "P82B96DGKR": ("logic", "U9, U13"),
    "TPS73033DBVR": ("logic", "U10"),
    "LM27313XQMFNOPB": ("logic", "U6"),
    "LMH6642MFNOPB": ("logic", "U12"),
    "TMUX1219DCKR": ("logic", "U1, U5, U7, U8"),
    "TPD4E004DRYR": ("logic", "U3"),
    # --- Power Stage ---------------------------------------------------------
    "BUK6D43-40PX": ("power", "Q1"),
    "RBR3LAM40ATR": ("power", "D1"),
    "SZMM3Z10VST1G": ("power", "D8"),
    # --- Connectors & Interconnect ------------------------------------------
    "50-57-9404": ("connect", "H9, H10"),
    "1051640001": ("connect", "J2"),
    "D3082-05": ("connect", "TP26-TP29"),
    # --- Capacitors ----------------------------------------------------------
    "885012207103": ("caps", "C15"),
    "CL31B105KCHNNNE": ("caps", "C17"),
    "EMK107B7105KAHT": ("caps", "C9, C26"),
    "EMK107BB7225KA-T": ("caps", "C16"),
    "0603ZC104KAT2A": ("caps", "C7, C8, C10, C11, C13"),
    "C0402C102J3GACTU": ("caps", "C25"),
    # --- Resistors -----------------------------------------------------------
    "RCA12060000ZSEA": ("res", "R36"),
    "HCJ0805ZT0R00": ("res", "R1"),
    "RC0603JR-07470RL": ("res", "R32, R33"),
    "RT0603BRC07500RL": ("res", "R28"),
    "RT0603DRE07117KL": ("res", "R4"),
    "RT0603DRE0713K3L": ("res", "R7"),
    "CRCW060310K0JNEA": ("res", "R35"),
    "CRCW0603150KFKEA": ("res", "R8, R9, R15, R16"),
    "CRCW0402680RJNED": ("res", "R34"),
    # --- Optoelectronics -----------------------------------------------------
    "150060BS75000": ("opto", "D9"),
    "150080VS75000": ("opto", "D2, D4"),
    "LTST-C190KRKT": ("opto", "D6"),
    "LTST-C190KGKT": ("opto", "D7"),
}

SUB_META = [
    ("logic", "Control & Logic ICs", "Microcontroller, amplifiers, bus buffers, regulators"),
    ("power", "Power Stage", "MOSFET, Schottky and Zener diodes"),
    ("connect", "Connectors & Interconnect", "USB receptacle, housings, shorting plugs"),
    ("caps", "Capacitors (MLCC)", "Multilayer ceramic chip capacitors"),
    ("res", "Resistors", "Thick/thin film chip resistors"),
    ("opto", "Optoelectronics", "Indicator LEDs"),
]


def main():
    per_part = collections.defaultdict(collections.Counter)
    cats = {}
    for row in csv.DictReader(SRC.open(encoding="utf-8")):
        part = row["source_file"].rsplit(".", 1)[0]
        per_part[part][row["material"]] += float(row["weight_mg"] or 0)
        cats[row["material"]] = row["category"]

    unmapped = sorted(set(per_part) - set(SUBASSEMBLY))
    if unmapped:
        raise SystemExit(f"Unmapped parts, add them to SUBASSEMBLY: {unmapped}")

    subs = []
    for sub_id, name, desc in SUB_META:
        parts = []
        rollup = collections.Counter()
        for part, (sid, desig) in SUBASSEMBLY.items():
            if sid != sub_id:
                continue
            mats = per_part[part]
            rollup.update(mats)
            parts.append({
                "part": part,
                "designators": desig,
                "weight": round(sum(mats.values()), 4),
                "materials": [
                    {"material": m, "weight": round(w, 6)}
                    for m, w in mats.most_common()
                ],
            })
        parts.sort(key=lambda p: -p["weight"])
        subs.append({
            "id": sub_id,
            "name": name,
            "description": desc,
            "partCount": len(parts),
            "weight": round(sum(rollup.values()), 4),
            "parts": parts,
            "materials": [
                {"material": m, "category": cats[m], "weight": round(w, 6)}
                for m, w in rollup.most_common()
            ],
        })
    subs.sort(key=lambda s: -s["weight"])

    payload = {
        "subassemblies": subs,
        "partCount": len(SUBASSEMBLY),
        "totalWeight": round(sum(s["weight"] for s in subs), 4),
    }
    DEST.write_text(
        "// Auto-generated by material_extractor/build_dashboard_data.py — do not edit by hand.\n"
        "const parts = " + json.dumps(payload, indent=2) + ";\nexport default parts;\n",
        encoding="utf-8",
    )
    print(f"wrote {DEST} — {len(subs)} sub-assemblies, {payload['totalWeight']} mg")


if __name__ == "__main__":
    main()
